---
format:  
  html:
    grid:
      margin-width: 350px
title: "Publications"
title-block-banner: pub_header.jpg
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: center;
        height: 200px;
      }
      </style>
---

# 2025

Barrio, I, Vuorinen K, Barbero Palacios L, Defourneaux M, Petit Bon M,… **Hayes K**, … Kamena S. Emerging priorities in terrestrial herbivory research in the Arctic. (2025). *Arctic Science.* <https://doi.org/10.1139/as-2024-0080>

Carter T, Stears A, Fornwalt P, Atkins D, Dwire K, Fleri J, **Hayes K**, Mount H, Twaddell E, Wessel S, Buma B, Laughlin D.Fine-root traits coordinate with aboveground strategies yet poorly predict species’ response to spruce mortality. (2025). *Plant Soil.* https://doi.org/10.1007/s11104-025-07463-x

# 2024

**Hayes K**, Hoffman C, Linn R, Ziegler J, Buma B. Fuel constraints, not fire weather conditions, limit fire behavior in reburned boreal forests. (2024). *Agricultural and Forest Meteorology*. <https://doi.org/10.1016/j.agrformet.2024.110216>

# 2023

Weiss S, Marshall A, **Hayes K**, Nicolsky D, Buma B, Lucash M. Future transitions from a conifer to a deciduous-dominated landscape are accelerated by greater wildfire activity and climate change in interior Alaska. (2023). *Landscape Ecology.* https://doi.org/10.1007/s10980-023-01733-8

# 2022

Carter T, **Hayes K**, Buma B. Putting more fuel on the fire… or maybe not? A synthesis of spruce beetle and fire interactions in North American Subalpine Forests. (2022). *Landscape Ecology*. <https://doi.org/10.1007/s10980-022-01481-1>

**Hayes K,** Carter T, Cook P, Twaddell E, Buma B. Supporting Graduate Field Leadership through Community-Sourced Advice, Action, and Policy. (2022). *Ecosphere.* <https://doi.org/10.1002/ecs2.4247>

Buma B, **Hayes K,** Weiss S, Lucash M. Short interval fires increasing in the Alaskan boreal forest as fire self-regulation decays across forest types. (2022). *Scientific Reports*. <https://doi.org/10.1038/s41598-022-08912-8>

Muthukrishnan R, **Hayes K**, Bartowitz K, Cattau M, Harvey B, Lin Y, Lunch C. Harnessing NEON to evaluate ecological tipping points: opportunities, challenges, and approaches. (2022). *Ecosphere*. [http://doi.org/10.1002/ecs2.3989](http://doi.org/10.1002/ecs2.3989%5d)

# 2021

Nagy C, Balch J, Bissell E, Cattau M, Glenn N, Halpern B, … **Hayes K**, … O’Riordan, C. Harnessing the NEON data revolution to advance open environmental science with a diverse and data‐capable community. (2021). *Ecosphere*. [https://doi.org/10.1002/ecs2.3833](#0)

**Hayes K**, Buma B. Effects of short-interval disturbances continue to accumulate, overwhelming variability in local resilience. (2021). *Ecosphere.* <https://doi.org/10.1002/ecs2.3379>

Jensen A, Fastovich D, Watson B, Gill J, Jackson S, Russell J, Bevington J, **Hayes K**, …. Williams J. More than one way to kill a spruce forest: The role of fire and climate in the late‐glacial termination of spruce woodlands across the southern Great Lakes. (2021). *Journal of Ecology*.<https://doi.org/10.1111/1365-2745.13517>

# 2020

Buma B, Weiss S, **Hayes K**, Lucash M. Wildland fire reburning trends across the US West suggest only short-term negative feedback and differing climatic effects. (2020). *Environmental Research Letters*. [https://doi.org/10.1088/1748-9326/ab6c70](#0)
