---
format:  
  html:
    grid:
      margin-width: 350px
title: "Come work with us"
title-block-banner: recruit_header.jpg
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: center;
        height: 200px;
      }
      </style>
---

Interested in joining the lab? Open positions, if available, will be posted below:

> The [Forest Ecosystem Research Applications Lab ](https://feral-lab.org/)at the [University of Alaska Fairbanks](https://www.uaf.edu/uaf/index.php) invites applications for a Postdoc or Data scientist interested in applying process-based simulation modeling to management and climate adaptation issues in the boreal forests of Interior Alaska. This position will contribute to an ongoing project, co-produced with managers, that identifies climate-smart opportunities for co-benefits of fire management. We seek a postdoc or data scientist who can calibrate and apply [iLand](https://iland-model.org/startpage), a forest and disturbance model, to test the efficacy and long-term outcomes of climate-smart fire management strategies. This position will involve working closely with a diverse group of research partners including the Alaska Climate Adaptation Science Center, the Alaska Fire Science Consortium and the US Fish and Wildlife Service. The postdoc will contribute to a growing lab group and will be welcomed into a vibrant and well-connected network of iLand users in North America and beyond.
>
> This is a full time position, with benefits, for one-year. Additional years are possible, based on performance and funding. Start date is flexible: the position can begin in Summer or Fall of 2026, according to candidate's availability. The position can be in-person, hybrid or remote - funds are available for travel and professional development.
>
> Specific responsibilities will include:
>
> -   Work closely with project lead and collaborators to parameterize, test and apply iLand to simulate fire management strategies in boreal ecosystems under future climate.
>
> -   Process, synthesize, interpret and visualize model outputs, communicating results in oral presentations and through peer-reviewed journal articles.
>
> -   Present results to research partners, through webinars, management meetings and internal team meetings.
>
> Applicants must have completed a Ph.D. in forest ecology, disturbance ecology, ecosystem modeling or some similar field prior to appointment. The ideal candidate will have advanced computational and programming skills, experience publishing peer-reviewed manuscripts and a demonstrated record of seeing projects through from start to finish. Experience in the following areas will be preferred: process-based simulation modeling, boreal forest ecosystem dynamics, fire ecology, research co-production. Priority will be given for excellent verbal and written skills and the interest and ability to interface with a diverse group of research partners. Most successful candidates do not meet all qualifications! If you have some of these skills, please consider applying.
>
> Questions? Want more information? Please contact Kate Hayes ([khayes23\@alaska.edu](mailto:khayes23@alaska.edu)).
>
> To apply, please send your cover letter addressing your experience and qualifications in relation to the responsibilities of this position, a curriculum vitae, and contact information for three references to Kate Hayes (khayes23\@alaska.edu). The position will remain open until filled.

As a lab, we aspire to create a diverse community that welcomes people of different races, cultures, ages, genders, sexuality, religions, socioeconomic levels, political perspectives, abilities, opinions, values and experiences.

# Undergraduate Research

Are you an undergraduate student at UAF interested in research? Get in touch! Happy to collaborate on internal opportunities like the [URSA](https://www.uaf.edu/ursa/) program.

## Graduate Opportunities

Curious about grad school? Interested in a master's or PhD in natural resources, environment or earth science? You can [email me (Kate)](mailto:khayes23@alaska.edu). Before you do, take a look through the lab website, especially the research page. Be prepared to talk about why you'd like to go to graduate school, and why you'd like to work with me in particular.

I'm also happy to talk about, develop and collaborate on proposals for independent funding proposals for the [NSF GRFP](https://www.nsfgrfp.org/) and others.

## Postdoc Researchers

Interested in a postdoc? Please [email me](mailto:khayes23@alaska.edu) to discuss potential projects. I'm happy to talk about, develop and collaborate on proposals for independent funding like [NSF's Postdoctoral Research Fellowships](http://nsf.gov/funding/postdocs), the USDA-NIFA or others.
